from playwright.async_api import async_playwright


async def create_pdf_from_html(html_content: str, title: str) -> bytes:
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()

        full_content = f"<h1>{title}</h1>\n{html_content}"

        with open("pdf_template.html", "r") as f:
            html_template = f.read()

        footer_html = """
<div style="
  width: 100%;
  height: 100%;
  background-color: #0A0F14;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
  font-family: sans-serif;
  font-size: 9px;
  color: #8B98A6;
">
  <div style="
    padding: 0 30px 8px; /* Left/right padding + bottom padding */
    border-top: 1px solid #2A3B4F;
  ">
    <div style="
      text-align: center;
      padding-top: 8px;
    ">
      <span>Generated by Cognis.dev</span> | 
      <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
    </div>
  </div>
</div>
"""

        final_html = html_template.replace("{content}", full_content)
        await page.set_content(final_html)
        await page.wait_for_load_state("networkidle")

        pdf_bytes = await page.pdf(
            format="A4",
            print_background=True,
            display_header_footer=True,
            header_template="<div></div>",
            footer_template=footer_html,
            scale=0.95,
        )

        await browser.close()
        return pdf_bytes
