"""Add status to content models, remove is_published

Revision ID: 16d3ce8bad53
Revises: 7df9a74c7243
Create Date: 2025-08-28 01:06:59.948604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

requeststatus = postgresql.ENUM("pending", "approved", "rejected", name="requeststatus")
requeststatus.create(op.get_bind(), checkfirst=True)
# revision identifiers, used by Alembic.
revision: str = "16d3ce8bad53"
down_revision: Union[str, None] = "7df9a74c7243"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chapters",
        sa.Column(
            "status",
            requeststatus,
            server_default="approved",
            nullable=False,
        ),
    )
    op.drop_column("chapters", "is_published")
    op.add_column(
        "exams",
        sa.Column(
            "status",
            requeststatus,
            server_default="pending",
            nullable=False,
        ),
    )
    op.drop_column("exams", "is_published")
    op.add_column(
        "resources",
        sa.Column(
            "status",
            requeststatus,
            server_default="pending",
            nullable=False,
        ),
    )
    op.drop_column("resources", "is_published")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resources",
        sa.Column(
            "is_published",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("resources", "status")
    op.add_column(
        "exams",
        sa.Column(
            "is_published",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("exams", "status")
    op.add_column(
        "chapters",
        sa.Column(
            "is_published",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("chapters", "status")
    # ### end Alembic commands ###
