"""Add user_id to chapters table

Revision ID: 2c81ddaac549
Revises: 4bcfb8525ec7
Create Date: 2025-08-27 19:53:13.941306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c81ddaac549'
down_revision: Union[str, None] = '4bcfb8525ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chapters', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.drop_column('chapters', 'user_id')
    # ### end Alembic commands ###
