"""Move visit_count from chapters to subjects

Revision ID: 39ee592f8738
Revises: f2869c1ce47d
Create Date: 2025-08-24 19:45:42.221140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ee592f8738'
down_revision: Union[str, None] = 'f2869c1ce47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'visit_count')
    op.add_column('subjects', sa.Column('visit_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'visit_count')
    op.add_column('chapters', sa.Column('visit_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
