"""Add visit_count to chapters table

Revision ID: f2869c1ce47d
Revises: 7c2a558afa96
Create Date: 2025-08-24 19:31:03.476712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2869c1ce47d"
down_revision: Union[str, None] = "7c2a558afa96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chapters",
        sa.Column(
            "visit_count",
            sa.Integer(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chapters", "visit_count")
    # ### end Alembic commands ###
